# dataset path 
train_path : 
val_path : 
test_path : 
submission_path : 

# trainer 
trainer : "BaseTrainer", "CNNTrainer"
criterion : "MSE", "Pearson"
metric : "Pearson"
optimizer : 
  type : "Adam"
  params :
    # 해당 optimizer에 맞는 parameter들 작성 
    lr : 
    weight_decay : 

early_stopping_patience : 50
save_intervals : 1
epochs : 10
batch_size : 128 
attention_based : True # 추후 attention 기반 모델은 시각화 할수 있도록 하기 위해 추가함 

# model
pre_trained_model_path : # 사전학습 모델 사용시, 허깅페이스 모델 경로 
# dataset_type, dataloader_type, architecture은 자신의 모델에 맞게 지정 후 추가
dataset_type : "CNN"
dataloader_type : "CNN"
architecture : "CNN"

# model specific : 각 모델에 맞게 작성 
num_filters : 100
filter_sizes :
  - 3
  - 4
  - 5
fc_sizes :
  - 300
  - 150
  - 1
dropout_rate : 0.2