# dataset path 
train_path : "../../data/train.csv"
val_path : "../../data/dev.csv"
test_path : "../../data/test.csv"
submission_path : "../../data/sample_submission.csv"


# pre_trained_model
pre_trained_path : 'sentence-transformers/paraphrase-multilingual-mpnet-base-v2'

# Dataset, Dataloader
dataset_type : 'TogetherWithTypeToken'
dataloader_type : "NoCollatorDataloader"
max_length : 200
batch_size : 128

# train
trainer_name : 'TogetherWithDiffTypeSameLengthTrainer'
model_name : 'TogetherClassicication'
criterion : 'MSE+BCE'
pos_weight : 2.75
metric : 'Pearson'
optimizer : 
  type : 'Adam'
  params : 
    lr : 0.01
scheduler : 
  type : "ExponentialLR"
  params : 
    gamma : 0.9
  # type : "StepLR"
  # params : 
  #   step_size : 100
  #   gamma : 0.1

early_stop_patience : 100
save_intervals : 20
epochs : 1000

# model specific 

fc_hidden_sizes : 
  - 768
  - 1
dropout_rate : 0.4